# Generated by Django 3.2.7 on 2021-09-13 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0013_alter_attendance_is_first_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reception', models.IntegerField(blank=True, default=0, null=True)),
                ('nurse', models.IntegerField(blank=True, default=0, null=True)),
                ('doctor', models.IntegerField(blank=True, default=0, null=True)),
                ('lab', models.IntegerField(blank=True, default=0, null=True)),
                ('pharmacy', models.IntegerField(blank=True, default=0, null=True)),
                ('cashier', models.IntegerField(blank=True, default=0, null=True)),
                ('house_keeper', models.IntegerField(blank=True, default=0, null=True)),
                ('overall', models.IntegerField(blank=True, default=0, null=True)),
                ('opinion', models.CharField(blank=True, max_length=300, null=True)),
                ('best_staff', models.CharField(blank=True, max_length=300, null=True)),
                ('how_did_you_hear_abt_rabito', models.CharField(blank=True, max_length=300, null=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='hospital.patient')),
            ],
        ),
    ]
