# Generated by Django 3.2.7 on 2021-09-13 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_alter_attendance_is_first_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing', '0002_auto_20210913_0404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='patient',
        ),
        migrations.AddField(
            model_name='feedback',
            name='attendant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='hospital.attendance'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='feedback',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
