# Generated by Django 3.2.7 on 2021-09-13 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_auto_20210913_0423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='attendant',
            new_name='attendance',
        ),
    ]
