# Generated by Django 3.2.7 on 2021-09-13 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_rename_attendant_feedback_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='ic_complete',
            field=models.BooleanField(default=False),
        ),
    ]
