# Generated by Django 3.2.7 on 2021-09-13 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_feedback_ic_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='ic_complete',
            new_name='is_complete',
        ),
    ]
