# Generated by Django 3.2.7 on 2021-10-10 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0006_rename_ic_complete_feedback_is_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('satisfied_percentage', models.IntegerField(default=0)),
                ('unsatisfied_percentage', models.IntegerField(default=0)),
                ('excellent_percentage', models.IntegerField(default=0)),
                ('very_good_percentage', models.IntegerField(default=0)),
                ('good_percentage', models.IntegerField(default=0)),
                ('fair', models.IntegerField(default=0)),
                ('bad', models.IntegerField(default=0)),
            ],
        ),
    ]
