# Generated by Django 3.2.7 on 2021-10-10 01:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_branch_code'),
        ('marketing', '0007_feedbackreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyBranchFeedbackReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('satisfied_percentage', models.IntegerField(default=0)),
                ('unsatisfied_percentage', models.IntegerField(default=0)),
                ('excellent_percentage', models.IntegerField(default=0)),
                ('very_good_percentage', models.IntegerField(default=0)),
                ('good_percentage', models.IntegerField(default=0)),
                ('fair', models.IntegerField(default=0)),
                ('bad', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_feedback', to='management.branch')),
            ],
        ),
        migrations.DeleteModel(
            name='FeedbackReport',
        ),
    ]
