# Generated by Django 3.2.6 on 2021-09-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('HR', 'HR'), ('CEO', 'CEO'), ('MARKETING', 'MARKETING'), ('DOCTOR', 'DOCTOR'), ('ADMIN', 'ADMIN'), ('NURSE', 'NURSE')], max_length=255, null=True),
        ),
    ]
