# Generated by Django 3.2.6 on 2021-09-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210907_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='end_time',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='start_time',
            new_name='start',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='subject',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='description',
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'ADMIN'), ('MARKETING', 'MARKETING'), ('NURSE', 'NURSE'), ('DOCTOR', 'DOCTOR'), ('CEO', 'CEO'), ('HR', 'HR')], max_length=255, null=True),
        ),
    ]
