# Generated by Django 3.2.6 on 2021-09-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210907_2210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='title',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='end',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='start',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('FEMALE', 'FEMALE'), ('MALE', 'MALE')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('CEO', 'CEO'), ('DOCTOR', 'DOCTOR'), ('MARKETING', 'MARKETING'), ('NURSE', 'NURSE'), ('HR', 'HR'), ('ADMIN', 'ADMIN')], max_length=255, null=True),
        ),
    ]
