# Generated by Django 3.2.6 on 2021-09-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210908_2036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='end_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('HR', 'HR'), ('DOCTOR', 'DOCTOR'), ('ADMIN', 'ADMIN'), ('CEO', 'CEO'), ('NURSE', 'NURSE'), ('MARKETING', 'MARKETING')], max_length=255, null=True),
        ),
    ]
