# Generated by Django 3.2.7 on 2021-09-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('FEMALE', 'FEMALE'), ('MALE', 'MALE')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('NURSE', 'NURSE'), ('ADMIN', 'ADMIN'), ('MARKETING', 'MARKETING'), ('HR', 'HR'), ('CEO', 'CEO'), ('DOCTOR', 'DOCTOR')], max_length=255, null=True),
        ),
    ]
