# Generated by Django 3.2.7 on 2021-09-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20210910_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='branch',
            new_name='branch_code',
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('HR', 'HR'), ('MARKETING', 'MARKETING'), ('ADMIN', 'ADMIN'), ('DOCTOR', 'DOCTOR'), ('NURSE', 'NURSE'), ('CEO', 'CEO')], max_length=255, null=True),
        ),
    ]
