# Generated by Django 3.2.7 on 2021-09-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('CEO', 'CEO'), ('MARKETING', 'MARKETING'), ('NURSE', 'NURSE'), ('HR', 'HR'), ('DOCTOR', 'DOCTOR'), ('ADMIN', 'ADMIN')], max_length=255, null=True),
        ),
    ]
