# Generated by Django 3.2.7 on 2021-09-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20210910_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('HR', 'HR'), ('NURSE', 'NURSE'), ('MARKETING', 'MARKETING'), ('DOCTOR', 'DOCTOR'), ('CEO', 'CEO'), ('ADMIN', 'ADMIN')], max_length=255, null=True),
        ),
    ]
