# Generated by Django 3.2.7 on 2021-09-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('NURSE', 'NURSE'), ('CEO', 'CEO'), ('ADMIN', 'ADMIN'), ('HR', 'HR'), ('MARKETING', 'MARKETING'), ('DOCTOR', 'DOCTOR')], max_length=255, null=True),
        ),
    ]
