# Generated by Django 3.2.7 on 2021-09-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20210910_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('CEO', 'CEO'), ('ADMIN', 'ADMIN'), ('NURSE', 'NURSE'), ('MARKETING', 'MARKETING'), ('HR', 'HR'), ('DOCTOR', 'DOCTOR')], max_length=255, null=True),
        ),
    ]
