# Generated by Django 3.2.7 on 2021-09-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('DOCTOR', 'DOCTOR'), ('CEO', 'CEO'), ('ADMIN', 'ADMIN'), ('HR', 'HR'), ('MARKETING', 'MARKETING'), ('NURSE', 'NURSE')], max_length=255, null=True),
        ),
    ]
