# Generated by Django 3.2.7 on 2021-09-13 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('NURSE', 'NURSE'), ('CEO', 'CEO'), ('DOCTOR', 'DOCTOR'), ('MARKETING', 'MARKETING'), ('HR', 'HR'), ('ADMIN', 'ADMIN')], max_length=255, null=True),
        ),
    ]
