# Generated by Django 3.2.7 on 2021-09-13 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_auto_20210913_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('CEO', 'CEO'), ('HR', 'HR'), ('MARKETING', 'MARKETING'), ('NURSE', 'NURSE'), ('ADMIN', 'ADMIN'), ('DOCTOR', 'DOCTOR')], max_length=255, null=True),
        ),
    ]
