# Generated by Django 3.2.7 on 2021-09-13 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('CEO', 'CEO'), ('DOCTOR', 'DOCTOR'), ('HR', 'HR'), ('NURSE', 'NURSE'), ('ADMIN', 'ADMIN'), ('MARKETING', 'MARKETING')], max_length=255, null=True),
        ),
    ]
