# Generated by Django 3.2.7 on 2021-09-13 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_auto_20210913_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('HR', 'HR'), ('DOCTOR', 'DOCTOR'), ('NURSE', 'NURSE'), ('CEO', 'CEO'), ('ADMIN', 'ADMIN'), ('MARKETING', 'MARKETING')], max_length=255, null=True),
        ),
    ]
