# Generated by Django 3.2.7 on 2021-10-10 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('DOCTOR', 'DOCTOR'), ('MARKETING', 'MARKETING'), ('HR', 'HR'), ('CEO', 'CEO'), ('NURSE', 'NURSE'), ('ADMIN', 'ADMIN')], max_length=255, null=True),
        ),
    ]
