# Generated by Django 3.2.7 on 2021-10-17 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_branch_code'),
        ('user', '0029_auto_20211010_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_branch', to='management.branch'),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.CharField(blank=True, choices=[('0500009652', '0500009652'), ('0200009652', '0200009652')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('CEO', 'CEO'), ('MARKETING', 'MARKETING'), ('NURSE', 'NURSE'), ('HR', 'HR'), ('DOCTOR', 'DOCTOR'), ('ADMIN', 'ADMIN')], max_length=255, null=True),
        ),
    ]
