# Generated by Django 3.2.7 on 2021-10-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_auto_20211017_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('HR', 'HR'), ('CEO', 'CEO'), ('NURSE', 'NURSE'), ('DOCTOR', 'DOCTOR'), ('ADMIN', 'ADMIN'), ('MARKETING', 'MARKETING')], max_length=255, null=True),
        ),
    ]
