# Generated by Django 3.2.6 on 2021-08-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
