# Generated by Django 3.2.6 on 2021-09-07 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_patient_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-first_name']},
        ),
    ]
