# Generated by Django 3.2.7 on 2021-09-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_auto_20210910_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_first_time',
            field=models.BooleanField(default=True),
        ),
    ]
