# Generated by Django 3.2.7 on 2021-09-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_patient_is_first_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_discharged',
            field=models.BooleanField(default=True),
        ),
    ]
