# Generated by Django 3.2.7 on 2021-09-10 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_auto_20210910_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='diagnoses',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='vital_signs',
        ),
    ]
