# Generated by Django 3.2.7 on 2021-09-10 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_auto_20210910_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_attendance', to='hospital.attendance'),
        ),
        migrations.AddField(
            model_name='note',
            name='attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_attendance', to='hospital.attendance'),
        ),
        migrations.AddField(
            model_name='vitalsign',
            name='attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vitals_attendance', to='hospital.attendance'),
        ),
    ]
