# Generated by Django 3.2.7 on 2021-09-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_auto_20210910_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ('-created_by',)},
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_walk_in',
            field=models.BooleanField(default=False),
        ),
    ]
