# Generated by Django 3.2.7 on 2021-09-13 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_auto_20210912_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_first_time',
            field=models.BooleanField(default=True),
        ),
    ]
