# Generated by Django 3.2.7 on 2021-09-13 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_attendance_is_first_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='is_first_time',
            field=models.BooleanField(default=False),
        ),
    ]
